### ISSUE TITLE
Uncaught TypeError: results is undefined

### ISSUE THREAD

**Issue by PepeMax** [bpk68/g-sheets-api#89] opened 2021-06-23 08:23 UTC
Is my js file.

```
const GSheetReader = require(['g-sheets-api']);

const options = {
  sheetId: '1_IpENDkoujmWr-B0M2ZVcyvgPQGeKwYxfHX_JYTDtRc',
  sheetNumber: 1,
  returnAllResults: true,
}

GSheetReader(options, results => {
  const table = document.createElement('table');
  const header = table.createTHead();
  const headerRow = header.insertRow(0);
  const tbody = table.createTBody();

  // First, create a header row
  Object.getOwnPropertyNames(results[0]).forEach(colName => {
    const cell = headerRow.insertCell(-1);
    cell.innerHTML = colName;
  });

  // Next, fill the rest of the rows with the lovely data
  results.forEach(result => {
    const row = tbody.insertRow(-1);

    Object.keys(result).forEach(key => {
      const cell = row.insertCell(-1);
      cell.innerHTML = result[key];
    })
  });

  const main = document.querySelector('#output');
  main.innerHTML = "";
  main.append(table);
});
```

In chrome I get "**Cannot read property '0' of undefined**"

Even with your example I have the undefined

I do add @license RequireJS 2.3.6 for : const GSheetReader = require(['g-sheets-api']);

**Comment by bpk68** [comment] 2021-07-19 17:43
Hey @PepeMax, firstly apologies for the delay in getting to you here, GitHub doesn't notify me about issues raised like this so it appears to have fallen through the cracks. 

There's nothing wrong with the demo code so I'm inclined to think there's something missing elsewhere. 

I'll look at this tomorrow to double-check everything, but one thing I've noticed in your shared code is that you have this line right at the top of your js file:

```javascript
const GSheetReader = require(['g-sheets-api']);
```

It looks like you're trying to import the library as an array. If you change it to this:

```javascript
const GSheetReader = require('g-sheets-api');
```

You might have more luck right away 😊

**Comment by bpk68** [comment] 2021-07-27 11:23
I've had a good look at this and a play about with lots of different demo sheets and I can't reproduce this error. I'm going to close this issue, but do let me know if you're still getting problems. 

I think the next step will be to have access to some code so I can look at how you're using it to see where the problem is 😊

**Closed by bpk68** 2021-07-27 11:23 UTC
